pipeline {
    agent any
    stages {
        stage('Branch Info') {
            steps {
                echo "Current branch: ${env.BRANCH_NAME}"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Complete') {
            steps {
                echo 'Job completed!'
            }
        }
        stage('Last Stage') {
            steps {
                echo 'Job completed!'
            }
        }
    }
}
